application: prog1box
version: 1
runtime: python27
threadsafe: no
api_version: 1

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: bootstrap/css

- url: /js
  static_dir: bootstrap/js

- url: /assets
  static_dir: bootstrap/assets

- url: /admin.css
  static_files: admin.css
  upload: admin.css

- url: '/admin/.*'
  login: admin
  script: admin.app

- url: '/u/.*'
  login: required
  script: dashboard.app

- url: .*
  script: main.app
